version: '3'
services:
  sirisoft_db:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: sirisoft
      MYSQL_USER: adabrain
      MYSQL_PASSWORD: 12345